services:
  smtp4dev:
    image: rnwood/smtp4dev
    container_name: smtp4dev
    restart: unless-stopped
    ports:
      - "1025:25"
      - "5005:80"
    environment:
      ServerOptions__TlsMode: "None"
      ServerOptions__AuthenticationRequired: "true"
      ServerOptions__SmtpAllowAnyCredentials: "true"

  remedy-mock:
    build:
      context: ./mocks/remedy
    container_name: remedy-mock
    restart: unless-stopped
    ports:
      - "40230:8080"
    volumes:
      - ./mocks/remedy/data:/app/data